== 지원폼

=== 지원자들의 프로세스 일괄 수정

==== 성공

operation::applyform/submit[snippets="http-request,path-parameters,request-fields,http-response"]

==== 실패: 개인정보 활용 거부

operation::applicant/submit-fail/reject-personal-data-collection[snippets="http-request,path-parameters,request-fields,http-response"]

==== 실패: 지원자 정보 누락

operation::applicant/submit-fail/invalid-applicant-info[snippets="http-request,path-parameters,request-fields,http-response"]

==== 실패: 잘못된 답변

operation::applicant/submit-fail/invalid-answers[snippets="http-request,path-parameters,request-fields,http-response"]

==== 실패: 대시보드 내에 프로세스 존재하지 않을 경우

operation::applicant/submit-fail/no-process[snippets="http-request,path-parameters,request-fields,http-response"]

=== 지원폼 조회

==== 성공

operation::applicant/read-applyform[snippets="http-request,path-parameters,http-response,response-fields"]

==== 실패: 존재하지 않는 지원폼

operation::applicant/read-applyform-fail/applyform-not-found[snippets="http-request,path-parameters,http-response"]

=== 지원폼 수정

==== 성공

operation::applicant/update[snippets="http-request,path-parameters,http-response,response-fields"]
