== 사용자

=== 사용자 회원가입

==== 성공

operation::member/signup[snippets="http-request,request-fields,http-response"]

==== 실패: 유효하지 않은 요청

operation::member/signup-fail/invalid-request[snippets="http-request,request-fields,http-response"]

==== 실패: 인증되지 않은 이메일

operation::member/signup-fail/not-verified-email[snippets="http-request,request-fields,http-response"]

=== 사용자 이메일 변경

==== 성공

operation::member/change-email[snippets="http-request,request-cookies,path-parameters,request-fields,http-response"]

==== 실패: 인증되지 않은 사용자 이메일

operation::member/change-email-fail/not-verified-email[snippets="http-request,request-cookies,path-parameters,request-fields,http-response"]

==== 실패: 적절하지 않은 이메일 형식

operation::member/change-email-fail/invalid-email[snippets="http-request,request-cookies,path-parameters,request-fields,http-response"]

=== 사용자 비밀번호 변경

==== 성공

operation::member/change-password[snippets="http-request,request-cookies,path-parameters,request-fields,http-response"]

==== 실패: 적절하지 않은 비밀번호 형식

operation::member/change-password-fail/invalid-password[snippets="http-request,request-cookies,path-parameters,request-fields,http-response"]
